### PR TITLE
Improve avatar image sizes

### PR DESCRIPTION
**Pull request by fpellet**
Hello,

The goal is to display the image at the right size depending on the page.

It also allows to have different implementations of the avatar repository.
I would like in another PR to propose an implementation with the Cloudinary service.

I have introduced two new configuration keys:
- `gravatars_pattern`: allows to choose the default gravatar pattern.
- `avatar_custom_link_accepted`: allows to forbid the user to customize the avatar via a url.

### CODE REVIEW

**Comment by albogdano** [comment]
I like the implementation and I'm in favor of SOLID, but it brings more problems than it solves. For example, in Scoold Pro all images (avatars, etc.) are handled the same like any other files and are uploaded in the same place (cloud storage). Here, we start having a separate service just for avatars and this is where things get complicated. This is the reason why I chose Scoold to work with URL only. And this is also the reason why Imgur may be deprecated soon, because it doesn't support files other than images. 
So my questions are:
- If this gets merged, how do you plan to add support for Cloudinary without implementing file uploads to Cloudinary?
- What about URLs to images inside Scoold posts (questions and answers)? How will they be moderated?

**Comment by fpellet** [comment]
`If this gets merged, how do you plan to add support for Cloudinary without implementing file uploads to Cloudinary?`  
Two solutions: use the Cloudinary widget or use an ajax request. 
After, Cloudinary sends me a url (in js, without backend) and I can transfer the url to Scoold as a custom link. After an implementation of AvatarRepository allowing to switch from one size to another.

`What about URLs to images inside Scoold posts (questions and answers)? How will they be moderated?`
In my case, I don't have the problem and I would like to ban images in posts.
But in any case, the problem is not the same. Avatars are displayed on many pages, on mails, and with different sizes. Which is very different from other files.
I remind that this PR, does not change the way images are stored, but improves the support of gravatar with the use of optimized image size.

**Comment by fpellet** [comment]
if you prefer, I renamed AvatarRepository to AvatarProvider and removed the `store` method: https://github.com/fpellet/scoold/pull/1

**Comment by albogdano** [comment]
Alright, I will need some more time to review this before merging.

**Comment by albogdano** [comment]
Merged this with some minor modifications.
I plan to implement `ImgurAvatarRepository` soon.

**Pull request merged**
