### PR TITLE
Added Chinese Translation

### PR DESCRIPTION
**Pull request by ky0ncheng**
Traditional Chinese and Simplified Chinese

### CODE REVIEW

**Comment by albogdano** [comment]
Thank you @ky0ncheng! Just to clarify, Scoold doesn't yet support loading files for different variants of the same locale (`zh_cn` and `zh_tw`) so for now it will only load the Simplified variant from `lang_zh.properties`. In the future, I might add this feature.

**Comment by ky0ncheng** [comment]
I think there are difference words. such as https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes

**Comment by albogdano** [comment]
It should work as expected now, see https://live.scoold.com/languages

**Comment by ky0ncheng** [comment]
Thanks.

**Pull request merged**
